name: EC2 Pipeline with Artifacts in S3

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

  ec2-job:
    runs-on: ubuntu-latest
    steps:
      - name: Launch EC2 Instance
        id: ec2
        run: |
          # Launch EC2 instance using AWS CLI
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-014d544cfef21b42d \
            --count 1 \
            --instance-type t2.micro \
            --key-name key-01d3ba78ff072d2b2 \
            --security-group-ids 683395501335 \
            --subnet-id subnet-0d6a48aa0ad0c19a4 \
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "EC2 Instance ID: $INSTANCE_ID"
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Wait for EC2 instance to be running
        run: |
          # Use AWS CLI to wait for the instance to be running
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}
          echo "EC2 instance is running."

      - name: Run pipeline using SSM
        run: |
          # Run the pipeline command via SSM
          aws ssm send-command \
            --instance-ids ${{ env.INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["cd /home/ec2-user/CICD && ./pipeline.sh"]' \
            --comment "Running pipeline on EC2 instance"
          
      - name: Upload artifacts to S3
        run: |
          # Upload generated artifacts to S3
          aws s3 cp /path/to/artifacts s3://<bucket-name>/artifacts/ --recursive
