name: Run EC2 Pipeline and Upload to S3

on:
  push:
    branches:
      - main  # Trigger the pipeline when pushing to the `main` branch

jobs:
  deploy:
    name: Deploy to EC2 and Run Pipeline
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS credentials using GitHub secrets
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Update AWS CLI (if preexisting version found)
    - name: Update AWS CLI
      run: |
        if [ -x "$(command -v aws)" ]; then
          echo "AWS CLI is already installed. Updating..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
        else
          echo "AWS CLI not found. Installing..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        fi

    # Launch an EC2 instance dynamically (or use an existing instance ID)
    - name: Launch EC2 instance
      id: launch_ec2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-084568db4383264d4 \
          --count 1 \
          --instance-type t2.micro \
          --key-name key-03164e1218ba76631 \
          --security-group-ids ${{ secrets.AWS_SECURITY_GROUP_ID }} \
          --subnet-id ${{ secrets.AWS_SUBNET_ID }} \
          --associate-public-ip-address \
          --query 'Instances[0].InstanceId' \
          --output text)
        
        echo "Launched EC2 instance with ID: $INSTANCE_ID"
        echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT  # Set output for subsequent steps

    # Wait for the EC2 instance to be ready
    - name: Wait for EC2 instance to be ready
      run: |
        aws ec2 wait instance-running --instance-ids ${{ steps.launch_ec2.outputs.instance_id }}
        echo "EC2 instance is now running."

    # Install and check if SSM Agent is installed and running on EC2
    - name: Install and verify SSM agent on EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ec2-user@${{ steps.launch_ec2.outputs.instance_id }} << EOF
          sudo yum install -y amazon-ssm-agent
          sudo systemctl start amazon-ssm-agent
          sudo systemctl enable amazon-ssm-agent
          sudo systemctl status amazon-ssm-agent
        EOF

    # Send the pipeline script to EC2 and execute it using SSM
    - name: Run pipeline script on EC2 using SSM
      run: |
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids ${{ steps.launch_ec2.outputs.instance_id }} \
          --document-name "AWS-RunShellScript" \
          --comment "Running pipeline script" \
          --parameters 'commands=["cd /home/ec2-user && curl -O https://raw.githubusercontent.com/conveytopraveenkumar/CICD/main/Pipeline.sh && chmod +x Pipeline.sh && ./Pipeline.sh"]' \
          --output text \
          --query "Command.CommandId")
        echo "Pipeline script is running. Command ID: $COMMAND_ID"

    # Optionally upload artifacts to S3
    - name: Upload artifacts to S3
      run: |
        aws s3 cp /path/to/artifact s3://${{ secrets.S3_BUCKET_NAME }}/path/ --recursive
        echo "Artifacts uploaded to S3."

    # Clean up (Stop EC2 instance after pipeline execution)
    - name: Terminate EC2 instance after pipeline execution
      run: |
        aws ec2 terminate-instances --instance-ids ${{ steps.launch_ec2.outputs.instance_id }}
        echo "Terminated EC2 instance."

    # Done
    - name: Pipeline Complete
      run: echo "Pipeline execution completed and artifacts uploaded to S3."
