name: EC2 Pipeline with Artifacts in S3

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Ensure your region is stored in GitHub Secrets

  ec2-job:
    runs-on: ubuntu-latest
    steps:
      - name: Launch EC2 Instance
        id: ec2
        run: |
          # Make sure the AWS region is set
          export AWS_REGION=${{ secrets.AWS_REGION }}  # Set AWS region from GitHub Secrets

          # Launch EC2 instance using AWS CLI
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-014d544cfef21b42d \
            --count 1 \
            --instance-type t2.micro \
            --key-name key-01d3ba78ff072d2b2 \
            --security-group-ids 683395501335 \
            --subnet-id subnet-0d6a48aa0ad0c19a4 \
            --region $AWS_REGION \  # Ensure the region is passed to the AWS CLI
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "EC2 Instance ID: $INSTANCE_ID"
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Wait for EC2 instance to be running
        run: |
          # Use AWS CLI to wait for the instance to be running
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }} --region $AWS_REGION
          echo "EC2 instance is running."

      - name: Upload artifacts to S3
        run: |
          # Upload generated artifacts to S3
          aws s3 cp /path/to/artifacts s3://<bucket-name>/artifacts/ --recursive --region $AWS_REGION
