name: Run EC2 Pipeline and Upload to S3

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    name: Deploy to EC2 and Run Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set Unique Names for Resources
      run: |
        echo "SECURITY_GROUP_NAME=MySecurityGroup-$(date +%s)" >> $GITHUB_ENV
        echo "KEY_PAIR_NAME=my-ec2-key-pair-$(date +%s)" >> $GITHUB_ENV

    - name: Create Security Group
      run: |
        SECURITY_GROUP_ID=$(aws ec2 create-security-group \
          --group-name ${{ env.SECURITY_GROUP_NAME }} \
          --description "Security group for EC2 instance" \
          --query "GroupId" \
          --output text)
        echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> $GITHUB_ENV

        aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 22 --cidr 0.0.0.0/0
        aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 80 --cidr 0.0.0.0/0

    - name: Create Key Pair
      run: |
        aws ec2 create-key-pair \
          --key-name ${{ env.KEY_PAIR_NAME }} \
          --query "KeyMaterial" \
          --output text > ${{ env.KEY_PAIR_NAME }}.pem
        chmod 400 ${{ env.KEY_PAIR_NAME }}.pem

    - name: Launch EC2 Instance
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-084568db4383264d4 \
          --instance-type t2.micro \
          --iam-instance-profile Name="AmazonEC2RoleforSSM" \
          --key-name ${{ env.KEY_PAIR_NAME }} \
          --security-group-ids ${{ env.SECURITY_GROUP_ID }} \
          --associate-public-ip-address \
          --query "Instances[0].InstanceId" \
          --output text)
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

    - name: Wait for EC2 instance to be running
      run: |
        echo "Waiting for EC2 instance ${{ env.INSTANCE_ID }} to be running..."
        aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}
        echo "✅ EC2 instance is now running."

    - name: Check if SSM agent is online
      run: |
        STATUS=$(aws ssm describe-instance-information \
          --query "InstanceInformationList[?InstanceId=='${{ env.INSTANCE_ID }}'].PingStatus" \
          --output text)
        if [ "$STATUS" != "Online" ]; then
          echo "❌ SSM agent is not online on instance ${{ env.INSTANCE_ID }}."
          exit 1
        fi
        echo "✅ SSM agent is online on instance ${{ env.INSTANCE_ID }}."

    - name: Run pipeline script on EC2 via SSM
      run: |
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids ${{ env.INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Run pipeline script" \
          --parameters 'commands=["cd /home/ubuntu && curl -O https://raw.githubusercontent.com/conveytopraveenkumar/CICD/main/Pipeline.sh && chmod +x Pipeline.sh && ./Pipeline.sh"]' \
          --query "Command.CommandId" \
          --output text)
        echo "✅ SSM command sent. Command ID: $COMMAND_ID"

    - name: Notify about artifact upload
      run: |
        echo "ℹ️ Artifact upload should be handled inside the Pipeline.sh script on EC2."
        echo "Example to include inside your script:"
        echo "aws s3 cp /home/ubuntu/output/ s3://${{ secrets.S3_BUCKET_NAME }}/pipeline-artifacts/ --recursive"

    - name: Pipeline Complete
      run: echo "✅ Pipeline completed successfully."
