name: Run EC2 Pipeline and Upload to S3

on:
  push:
    branches:
      - main  # Trigger the pipeline when pushing to the `main` branch

jobs:
  deploy:
    name: Deploy to EC2 and Run Pipeline
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS credentials using GitHub secrets
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Update AWS CLI if needed
    - name: Ensure latest AWS CLI version
      run: |
        if [ -x "$(command -v aws)" ]; then
          echo "AWS CLI is already installed. Updating..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
        else
          echo "AWS CLI not found. Installing..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install
        fi

    # Wait for EC2 instance to be in 'running' state
    - name: Wait for EC2 instance to be running
      run: |
        INSTANCE_ID="i-0c6340dd26b28f109"  # Hardcoded instance ID
        echo "Waiting for EC2 instance $INSTANCE_ID to be running..."
        aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        echo "EC2 instance $INSTANCE_ID is now running."

    # Check if the EC2 instance has the SSM agent running
    - name: Check if EC2 instance has SSM agent running
      run: |
        INSTANCE_ID="i-0c6340dd26b28f109"
        echo "Checking SSM agent status on EC2 instance $INSTANCE_ID..."
        STATUS=$(aws ssm describe-instance-information --query "InstanceInformationList[?InstanceId=='$INSTANCE_ID'].PingStatus" --output text)
        if [ "$STATUS" != "Online" ]; then
          echo "SSM agent is not online. Ensure the agent is installed and running on the EC2 instance."
          exit 1
        fi
        echo "SSM agent is online on instance $INSTANCE_ID."

    # Run pipeline script on EC2
    - name: Run pipeline script on EC2
      run: |
        INSTANCE_ID="i-0c6340dd26b28f109"  # Hardcoded instance ID
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --comment "Running pipeline script from GitHub Actions" \
          --parameters 'commands=["cd /home/ec2-user && curl -O https://raw.githubusercontent.com/conveytopraveenkumar/CICD/main/Pipeline.sh && chmod +x Pipeline.sh && ./Pipeline.sh"]' \
          --output text \
          --query "Command.CommandId")
        echo "Pipeline script is running. Command ID: $COMMAND_ID"

    # Optionally upload artifacts to S3
    - name: Upload artifacts to S3
      run: |
        aws s3 cp /path/to/artifact s3://${{ secrets.S3_BUCKET_NAME }}/path/ --recursive
        echo "Artifacts uploaded to S3."

    # Clean up (Stop EC2 instance after pipeline execution)
    - name: Terminate EC2 instance after pipeline execution
      run: |
        aws ec2 terminate-instances --instance-ids $INSTANCE_ID
        echo "Terminated EC2 instance."

    # Done
    - name: Pipeline Complete
      run: echo "Pipeline execution completed and artifacts uploaded to S3."
